### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1nv3570rnn30m4** [Karlheinzniebuhr/torshammer#2]
i get this error if i run the python3 torshammer.py

Traceback (most recent call last):
  File "/home/user/Desktop/Tor/torshammer/torshammer.py", line 24, in <module>
    term = terminal.TerminalController()
  File "/home/user/Desktop/Tor/torshammer/terminal.py", line 106, in __init__
    setattr(self, attrib, self._tigetstr(cap_name) or '')
  File "/home/user/Desktop/Tor/torshammer/terminal.py", line 124, in _tigetstr
    return re.sub(r'\$<\d+>[/*]?', '', cap)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by xinxin11** [comment]
@1nv3570rnn30m4  same errors with you, have you fixed it ?

**Comment by Karlheinzniebuhr** [comment]
Can you please provide the exact command you used when this error appeared?
